name: theo-stac-demo
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - rasterio
  - xarray
  - rioxarray
  - pandas
  - pip
  - pip:
      - geogif
      - stackstac
      - pystac-client